# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from talk_capture._pb import meeting_pb2 as meeting__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in meeting_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeetingGatewayStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessCall = channel.stream_unary(
                '/meeting.v1.MeetingGateway/ProcessCall',
                request_serializer=meeting__pb2.CallFrame.SerializeToString,
                response_deserializer=meeting__pb2.CallAccepted.FromString,
                _registered_method=True)
        self.GetArtifacts = channel.unary_unary(
                '/meeting.v1.MeetingGateway/GetArtifacts',
                request_serializer=meeting__pb2.ArtifactsRequest.SerializeToString,
                response_deserializer=meeting__pb2.ArtifactsResponse.FromString,
                _registered_method=True)
        self.AckArtifacts = channel.unary_unary(
                '/meeting.v1.MeetingGateway/AckArtifacts',
                request_serializer=meeting__pb2.AckRequest.SerializeToString,
                response_deserializer=meeting__pb2.Ack.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/meeting.v1.MeetingGateway/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=meeting__pb2.HealthStatus.FromString,
                _registered_method=True)


class MeetingGatewayServicer:
    """Missing associated documentation comment in .proto file."""

    def ProcessCall(self, request_iterator, context):
        """Stream one call's audio. The first frame carries the meeting's context, then
        per-speaker audio, then an optional end frame just before half-close.

        Returns once the call is accepted and durably owned by us — NOT once the
        meeting is analysed. The transcript is usually ready at this point; analysis
        is not. Fetch both with GetArtifacts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifacts(self, request, context):
        """What is ready for this call so far. Safe to call repeatedly: it is the
        client's only way to learn that analysis finished, and re-fetching is how a
        client that crashed mid-write recovers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckArtifacts(self, request, context):
        """Tell us the client has durably written these artifacts, so we can retire
        them. Advisory: retention also expires on its own, and a client that never
        acks still works — it just re-fetches until the window closes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeetingGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessCall': grpc.stream_unary_rpc_method_handler(
                    servicer.ProcessCall,
                    request_deserializer=meeting__pb2.CallFrame.FromString,
                    response_serializer=meeting__pb2.CallAccepted.SerializeToString,
            ),
            'GetArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifacts,
                    request_deserializer=meeting__pb2.ArtifactsRequest.FromString,
                    response_serializer=meeting__pb2.ArtifactsResponse.SerializeToString,
            ),
            'AckArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.AckArtifacts,
                    request_deserializer=meeting__pb2.AckRequest.FromString,
                    response_serializer=meeting__pb2.Ack.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=meeting__pb2.HealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meeting.v1.MeetingGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meeting.v1.MeetingGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeetingGateway:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessCall(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/meeting.v1.MeetingGateway/ProcessCall',
            meeting__pb2.CallFrame.SerializeToString,
            meeting__pb2.CallAccepted.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeting.v1.MeetingGateway/GetArtifacts',
            meeting__pb2.ArtifactsRequest.SerializeToString,
            meeting__pb2.ArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeting.v1.MeetingGateway/AckArtifacts',
            meeting__pb2.AckRequest.SerializeToString,
            meeting__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meeting.v1.MeetingGateway/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            meeting__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
